---
Name: notifierconfig
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        NotificationMiddleware: '%ilateral\SilverStripe\Notifier\Middleware\NotificationMiddleware'
